announcer:
  ##Time in seconds
  time: 60
  ## usa ; para un salto de linea.
  list:
    - "&6%player% &fcompra rango u.u;esto es un salto de linea"
    - "&feditame esto por fi"
    - "&cTe lo dejo a tu criterio"
clear_lag:
  time: 60
  announcer: "&cse han borrado %amount% de items en el suelo"

percentage:
  ##Puedes incrementar el porcentaje con el permiso: "survival.headpercentage.5" < esto aumentaren un 5% el dropeo.
  head_drop: 1
  ##Para reducir el porcentaje usa el permiso, "survival.deadpercentage.10" > esto reduciren 10% el porcentaje de perdida.
  dead_money: 100
  ##Para reducir el porcentaje usa el permiso, "survival.lostxp.10" > esto reduciren 10% el porcentaje de perdida.
  lost_xp: 100
tablist:
  header: "&7
           &6&lSurvival
           &8  "
  footer: "&7
           &9&lWWW.MINELC.NET
           &a&lJugando en &e&lPLAY.MINELC.NET
           &8  "

random_tp:
  ##world_name:
  ## - "teleport coordinates"
  Recursos:
    ## "x,y,z,pitch,yaw"
    - "15.5,45.5,59.5,7,8"
scoreboard:
  title: "&6Survival"
  rows:
    - "&7&m                &f"
    - "&fMoney:"
    - "%money_prefix%"
    - "&fWorld:"
    - "%world%"
    - "Plot:"
    - "%plotname%"
    - "etc"
    - "etc"
    - "etc"
    - "etc"
    - "etc"
    - "etc"
    - "&eplay.minelc.net"
    - "&7&m                &c"